//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace WcfOutApp.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyErrorObject", Namespace="http://schemas.datacontract.org/2004/07/WCFOutParam")]
    public partial class MyErrorObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.SomeService")]
    public interface SomeService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:SomeService/GetSomeData", ReplyAction="urn:SomeService/GetSomeDataResponse")]
        System.IAsyncResult BeginGetSomeData(int Id, System.AsyncCallback callback, object asyncState);
        
        string EndGetSomeData(out WcfOutApp.ServiceReference1.MyErrorObject myError, System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SomeServiceChannel : WcfOutApp.ServiceReference1.SomeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetSomeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSomeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WcfOutApp.ServiceReference1.MyErrorObject myError {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WcfOutApp.ServiceReference1.MyErrorObject)(this.results[0]));
            }
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SomeServiceClient : System.ServiceModel.ClientBase<WcfOutApp.ServiceReference1.SomeService>, WcfOutApp.ServiceReference1.SomeService {
        
        private BeginOperationDelegate onBeginGetSomeDataDelegate;
        
        private EndOperationDelegate onEndGetSomeDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetSomeDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SomeServiceClient() {
        }
        
        public SomeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SomeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetSomeDataCompletedEventArgs> GetSomeDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WcfOutApp.ServiceReference1.SomeService.BeginGetSomeData(int Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSomeData(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WcfOutApp.ServiceReference1.SomeService.EndGetSomeData(out WcfOutApp.ServiceReference1.MyErrorObject myError, System.IAsyncResult result) {
            return base.Channel.EndGetSomeData(out myError, result);
        }
        
        private System.IAsyncResult OnBeginGetSomeData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            return ((WcfOutApp.ServiceReference1.SomeService)(this)).BeginGetSomeData(Id, callback, asyncState);
        }
        
        private object[] OnEndGetSomeData(System.IAsyncResult result) {
            WcfOutApp.ServiceReference1.MyErrorObject myError = this.GetDefaultValueForInitialization<WcfOutApp.ServiceReference1.MyErrorObject>();
            string retVal = ((WcfOutApp.ServiceReference1.SomeService)(this)).EndGetSomeData(out myError, result);
            return new object[] {
                    myError,
                    retVal};
        }
        
        private void OnGetSomeDataCompleted(object state) {
            if ((this.GetSomeDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSomeDataCompleted(this, new GetSomeDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSomeDataAsync(int Id) {
            this.GetSomeDataAsync(Id, null);
        }
        
        public void GetSomeDataAsync(int Id, object userState) {
            if ((this.onBeginGetSomeDataDelegate == null)) {
                this.onBeginGetSomeDataDelegate = new BeginOperationDelegate(this.OnBeginGetSomeData);
            }
            if ((this.onEndGetSomeDataDelegate == null)) {
                this.onEndGetSomeDataDelegate = new EndOperationDelegate(this.OnEndGetSomeData);
            }
            if ((this.onGetSomeDataCompletedDelegate == null)) {
                this.onGetSomeDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSomeDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetSomeDataDelegate, new object[] {
                        Id}, this.onEndGetSomeDataDelegate, this.onGetSomeDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WcfOutApp.ServiceReference1.SomeService CreateChannel() {
            return new SomeServiceClientChannel(this);
        }
        
        private class SomeServiceClientChannel : ChannelBase<WcfOutApp.ServiceReference1.SomeService>, WcfOutApp.ServiceReference1.SomeService {
            
            public SomeServiceClientChannel(System.ServiceModel.ClientBase<WcfOutApp.ServiceReference1.SomeService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSomeData(int Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("GetSomeData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetSomeData(out WcfOutApp.ServiceReference1.MyErrorObject myError, System.IAsyncResult result) {
                object[] _args = new object[1];
                string _result = ((string)(base.EndInvoke("GetSomeData", _args, result)));
                myError = ((WcfOutApp.ServiceReference1.MyErrorObject)(_args[0]));
                return _result;
            }
        }
    }
}
